version: "3.8"

services:
  # Main application service
  beacompanion-app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      # Database configuration (update with your values)
      - DB_HOST=${DB_HOST:-srv609.hstgr.io}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-u797570272_root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-u797570272_beacompanion}
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-here}
      # Email configuration
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      # Development volume mounts (comment out for production)
      - ./server:/app/server:ro
      - ./machine-learning:/app/machine-learning:ro
      # Persistent data
      - ml_models:/app/machine-learning/models
      - app_logs:/app/logs
    networks:
      - beacompanion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/ml/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - beacompanion-app
    networks:
      - beacompanion-network
    restart: unless-stopped
    profiles:
      - production

  # Optional: Database service for local development
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-beacompanion_local}
      - MYSQL_USER=${DB_USER:-beacompanion}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - beacompanion-network
    restart: unless-stopped
    profiles:
      - local

volumes:
  ml_models:
    driver: local
  app_logs:
    driver: local
  mysql_data:
    driver: local

networks:
  beacompanion-network:
    driver: bridge
